import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/index.css";
import "./styles/app.css";
import "./styles/dice.css";
import PrivyProvider from "./components/PrivyProvider";
import { AppConfigProvider } from "./components/AppConfigProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppConfigProvider>
          <PrivyProvider>{children}</PrivyProvider>
                  </AppConfigProvider>
      </body>
    </html>
  );
}
